### ISSUE TITLE
build fails building tikv-jemalloc-sys

### ISSUE THREAD

**Issue by dantrevino** [stacks-archive/sbtc-developer-release#420]
### Expected Behavior

dev build fails

```
146.1   running: cd "/src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/build" && "make" "-j" "8"
146.1
146.1   --- stderr
146.1   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tikv-jemalloc-sys-0.5.4+5.3.0-patched/build.rs:347:19:
146.1   failed to execute command: No such file or directory (os error 2)
146.1   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
146.1 warning: build failed, waiting for other jobs to finish...
------
failed to solve: process "/bin/sh -c cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release" did not complete successfully: exit code: 101
```

### Steps to Reproduce
1. clone sbtc repo
2. cd `devenv`
3. `build.sh`

env:
`Linux infinity 6.5.0-10027-tuxedo #31 SMP PREEMPT_DYNAMIC Tue Mar  5 10:45:49 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux`
`cargo 1.77.2 (e52e36006 2024-03-26)`
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="TUXEDO OS 2 22.04.4 LTS"`

`Docker version 26.0.1, build d260a54`

`docker-compose version 1.29.2, build unknown`

### Screenshots or Videos
```
146.1   ===============================================================================
146.1   jemalloc version   : 5.3.0-0-g54eaed1d8b56b1aa528be3bdd1877e59c56fa90c
146.1   library revision   : 2
146.1
146.1   CONFIG             : --disable-cxx --enable-doc=no --enable-shared=no --with-jemalloc-prefix=_rjem_ --with-private-namespace=_rjem_ --host=x86_64-unknown-linux-musl --build=x86_64-unknown-linux-musl --prefix=/src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out build_alias=x86_64-unknown-linux-musl host_alias=x86_64-unknown-linux-musl CC=cc 'CFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall' 'LDFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall' 'CPPFLAGS=-O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall'
146.1   CC                 : cc
146.1   CONFIGURE_CFLAGS   : -std=gnu11 -Wall -Wextra -Wsign-compare -Wundef -Wno-format-zero-length -Wpointer-arith -Wno-missing-braces -Wno-missing-field-initializers -Wno-missing-attributes -pipe -g3 -fvisibility=hidden -Wimplicit-fallthrough -O3 -funroll-loops
146.1   SPECIFIED_CFLAGS   : -O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall
146.1   EXTRA_CFLAGS       :
146.1   CPPFLAGS           : -O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall -D_GNU_SOURCE -D_REENTRANT
146.1   CXX                :
146.1   CONFIGURE_CXXFLAGS :
146.1   SPECIFIED_CXXFLAGS :
146.1   EXTRA_CXXFLAGS     :
146.1   LDFLAGS            : -O3 -ffunction-sections -fdata-sections -fPIC -gdwarf-4 -fno-omit-frame-pointer -m64 -Wall
146.1   EXTRA_LDFLAGS      :
146.1   DSO_LDFLAGS        : -shared -Wl,-soname,$(@F)
146.1   LIBS               : -pthread
146.1   RPATH_EXTRA        :
146.1
146.1   XSLTPROC           : false
146.1   XSLROOT            :
146.1
146.1   PREFIX             : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out
146.1   BINDIR             : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/bin
146.1   DATADIR            : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/share
146.1   INCLUDEDIR         : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/include
146.1   LIBDIR             : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/lib
146.1   MANDIR             : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/share/man
146.1
146.1   srcroot            :
146.1   abs_srcroot        : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/build/
146.1   objroot            :
146.1   abs_objroot        : /src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/build/
146.1
146.1   JEMALLOC_PREFIX    : _rjem_
146.1   JEMALLOC_PRIVATE_NAMESPACE
146.1                      : _rjem_je_
146.1   install_suffix     :
146.1   malloc_conf        :
146.1   documentation      : 0
146.1   shared libs        : 0
146.1   static libs        : 1
146.1   autogen            : 0
146.1   debug              : 0
146.1   stats              : 1
146.1   experimental_smallocx : 0
146.1   prof               : 0
146.1   prof-libunwind     : 0
146.1   prof-libgcc        : 0
146.1   prof-gcc           : 0
146.1   fill               : 1
146.1   utrace             : 0
146.1   xmalloc            : 0
146.1   log                : 0
146.1   lazy_lock          : 0
146.1   cache-oblivious    : 1
146.1   cxx                : 0
146.1   ===============================================================================
146.1   running: cd "/src/target/release/build/tikv-jemalloc-sys-e008728b252097b4/out/build" && "make" "-j" "8"
146.1
146.1   --- stderr
146.1   thread 'main' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/tikv-jemalloc-sys-0.5.4+5.3.0-patched/build.rs:347:19:
146.1   failed to execute command: No such file or directory (os error 2)
146.1   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
146.1 warning: build failed, waiting for other jobs to finish...
------
failed to solve: process "/bin/sh -c cd testnet/stacks-node && cargo build --features monitoring_prom,slog_json --release" did not complete successfully: exit code: 101```

**Comment by humblegorilla** [comment]
The same error happens on my Mac. Is it related to docker on mac?
